[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#090d16"
secondaryBackgroundColor = "#0f172a"
textColor = "#cbd5e1"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 600
